import { Metadata } from "next";

// meta tags
export const metadata: Metadata = {
  title: {
    // absolute: "", // ignore the template properties
    default: "Next.js tutorial 29.03.2024",
    template: "%s | Nazrifs", // first is the page title and followed by default suffix
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "ghostWhite",
            padding: "1rem",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
